#!/bin/bash

#SBATCH --job-name=transcribe_job
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=01:00:00
#SBATCH --output=transcribe_output.log

# Load the python3 module
module load python3


# Activate the virtual environment
source .venv/bin/activate

# Run the Python script and save the output
python3 transcribe_folder.py

# Deactivate the virtual environment
deactivate

# Delete the input_folder
rm -rf input_folder

# End of script
